version: '3.2'
services:
  jenkins:
    build: jenkins/.
    restart: always
    ports:
      - "127.0.0.1:50000:50000"
      - "127.0.0.1:8000:8080"
    expose:
      - "50000"
      - "8000"
    volumes:
      - /var/lib/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock